# Site
name: 'Adventures with TnT'
description: 'Description of site goes here'
#logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
#baseurl: '/mundana-theme-jekyll'
baseurl: ''
disqus: 'demowebsite'
email: 'wowthemesnet@gmail.com'
#mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    terri:
      name:           Terri Sluss-Cole
      #site:          https://www.facebook.com/terri.slusscole
      avatar:         assets/images/avatar.jpg
      bio:            "Fill in with your bio"
      email:          terrijsc@gmail.com
      twitter:        https://twitter.com/TerriJSC
      facebook:       https://www.facebook.com/terri.slusscole
      instagram:      https://www.instagram.com/terrijsc/
      linkedin:       https://www.linkedin.com/in/terri-sluss-cole-77996720/
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: terri
      avatar: /assets/images/avatar.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]